name: 문제 출제
description: 문제 출제 작성 양식입니다.
title: "[N주차/이름] 문제 제목"
body:
  - type: markdown
    attributes:
      value: |
        작성 예시: `[N주차/이름] 자유주제`

  - type: textarea
    id: quiz-contents
    attributes:
      label: 문제
      description: 출제할 문제에 대해 적어주세요.
      placeholder: 문제를 적어주세요.
    validations:
      required: true
